---
title: Gasoline Production Forecast
output: html_notebook
---



```{r}
# monthly gas production expressed in millions of barrels
library(forecast)
gas_prod_input <- as.data.frame( read.csv("gas_prod.csv") )

# creating a time series object
gas_prod <- ts(gas_prod_input[,2])

gas_prod
#examine the time series
plot(gas_prod, xlab = "Time (months)", ylab = "Gasoline production (millions of barrels)")
```

```{r}
#Dickey-Fuller Test for stationarity
library(tseries)
adf.test(gas_prod,alternative="stationary",k=0)
#making time series stationary
#differencing will help in making TS stationary i.e mean=0
# making time series stationary
plot(diff(gas_prod))  #differencing just once helped in making TS stationary i.e mean=0

abline(a=0, b=0)

```
```{r}
# examining ACF and PACF of differenced series

acf(diff(gas_prod), xaxp = c(0, 48, 4), lag.max=48, main="")  #gives MA terms
pacf(diff(gas_prod), xaxp = c(0, 48, 4), lag.max=48, main="")   #gives AR terms of the model
```


```{r}
Best=auto.arima(gas_prod,ic="aic",allowdrift = FALSE,trace = TRUE,approximation = TRUE)  # finds model having least AIC 
Best
fit=arima(gas_prod,order=c(0,1,1),seasonal = list(order=c(1,0,0),period=12))
fit
fit_residuals=residuals(fit)
#Checking if there is any autocorrelation
Box.test(fit_residuals,lag = 48,type="Ljung-Box")
AIC(fit,k = log(length(gas_prod)))   #BIC

```

```{r}
# examine ACF and PACF of the (0,1,1)x(1,0,0)12 residuals
acf(fit$residuals, xaxp = c(0, 48, 4), lag.max=48, main="")
pacf(fit$residuals, xaxp = c(0, 48,4), lag.max=48, main="")  #all variations are within CI

```

```{r}
# Forecasting

#predict the next 12 months
fit.predict <- predict(fit,n.ahead=12)
matrix(c(fit.predict$pred-1.96*fit.predict$se,
         fit.predict$pred,
         fit.predict$pred+1.96*fit.predict$se), 12,3,
       dimnames=list( c(241:252) ,c("LB","Pred","UB")) )

plot(gas_prod, xlim=c(145,252),
     xlab = "Time (months)",
     ylab = "Gasoline production (millions of barrels)",
     ylim=c(360,440))
lines(fit.predict$pred)
lines(fit.predict$pred+1.96*fit.predict$se, col=4, lty=2)   # 1.96 for 95% confidence interval,1.645 for 90%
lines(fit.predict$pred-1.96*fit.predict$se, col=4, lty=2)    
```
